version: '3.3'

services:
   catalogue:
     image: catalogue:latest
     build:
      context: Dockerfiles/Catalogue/ .
      dockerfile: Dockerfile
     ports:
       - "5001:5001"
     restart: always

   notes:
     image: notes:latest
     build:
      context: Dockerfiles/Notes/ .
      dockerfile: Dockerfile
     ports:
       - "5002:5002"
     restart: always

   recherche:
     image: recherche:latest
     build:
      context: Dockerfiles/Recherche/ .
      dockerfile: Dockerfile
     ports:
       - "5003:5003"
     restart: always

   netfleeks:
     image: netfleeks:latest
     build:
      context: Dockerfiles/Netfleeks/ .
      dockerfile: Dockerfile
     ports:
       - "8080:80"
     restart: always
       
volumes:
    volume_netfleeks: {}